### ISSUE TITLE
step 1: How to set up OTP so that API reacts on requests to API_URL?

### ISSUE THREAD

**Issue by dancesWithCycles** [stadtnavi/stadtnavi-tutorial#11]
Hi folks,
I have a UI instance running at this [address](https://vbn.hueja.dedriver.org/) and a OTP instance running at this [address](http://83.223.94.182:8080/). Now I am wondering how I make the API of this OTP instance able to be callable by the UI.

In this docu [step 1](https://github.com/stadtnavi/stadtnavi-tutorial/tree/main/01-installing-and-running-ui) you set `API_URL` the following way.

```const API_URL = process.env.API_URL || 'https://api.stadtnavi.de';```

Now I am wondering how to set up the OTP instance so I can configure the UI like above and both are able to reach each other.

I appreciate any hint pointing me in the right direction.

Cheers!

**Comment by leonardehrenfried** [comment]
Have you enabled the Graphql API? https://github.com/stadtnavi/digitransit-ansible/blob/master/roles/digitransit/templates/otp/otp-config.json#L3

**Comment by hbruch** [comment]
Be aware that api.stadtnavi.de acts as reverse proxy, delegating to different services. E.g. OTP requests are forwarded via

```
location /routing/v1/router {
    rewrite /routing/v1/router/(.*) /otp/routers/default/$1  break;
    ...
```

**Comment by dancesWithCycles** [comment]
Hi @leonardehrenfried ,
hi @hbruch ,
Thank you so much for  your prompt reply.

Indeed, I missed enabling the GraphQL API. Thanks for the hint. It is tough for me to find any details about the OTP API's, what they are capable of and how to work with them. I am no web developer. Do you have a hint how I can find out about all that from a non web developer point of view?

BTW, as we are talking, I like to share an observation I made now with the OTP config from the [ansible repo](https://github.com/stadtnavi/digitransit-ansible) and I did before.

Always when I use ```"osmWayPropertySet" : "germany"``` as build config I end up with the following error message.

```
$ java -Xmx7G -jar otp.jar --buildStreet .
03:20:08.560 INFO (OTPMain.java:36) OTP STARTED (version: 2.0.0, commit: a64576040edff06e84033f2e78991a5ba56b2f78, branch: v2.0.0)
03:20:08.586 INFO (OtpStartupInfo.java:41) 
  ___                 _____     _       ____  _                             
 / _ \ _ __   ___ _ _|_   _| __(_)_ __ |  _ \| | __ _ _ __  _ __   ___ _ __ 
| | | | '_ \ / _ \ '_ \| || '__| | '_ \| |_) | |/ _` | '_ \| '_ \ / _ \ '__|
| |_| | |_) |  __/ | | | || |  | | |_) |  __/| | (_| | | | | | | |  __/ |   
 \___/| .__/ \___|_| |_|_||_|  |_| .__/|_|   |_|\__,_|_| |_|_| |_|\___|_| 
      |_|                        |_| 
Version:  2.0.0
Commit:   a64576040edff06e84033f2e78991a5ba56b2f78
Branch:   v2.0.0
Build:    2020-11-27T13:02:08+0000

03:20:08.607 INFO (OTPMain.java:92) Searching for configuration and input files in /home/sib/vbn/otp/.
03:20:08.742 INFO (ConfigLoader.java:163) Load JSON configuration file './otp-config.json'
03:20:08.751 INFO (ConfigLoader.java:164) Summarizing './otp-config.json': {
  "otpFeatures" : {
    "SandboxAPILegacyGraphQLApi" : true,
    "SandboxAPIMapboxVectorTilesApi" : true,
    "FlexRouting" : true,
    "FloatingBike" : true
  }
}
03:20:08.760 WARN (NodeAdapter.java:352) Unexpected config parameter: 'otpFeatures.FloatingBike:true' in 'otp-config.json'. Is the spelling correct?
03:20:08.760 WARN (NodeAdapter.java:352) Unexpected config parameter: 'otpFeatures.SandboxAPIMapboxVectorTilesApi:true' in 'otp-config.json'. Is the spelling correct?
03:20:08.761 INFO (ConfigLoader.java:163) Load JSON configuration file './build-config.json'
03:20:08.762 INFO (ConfigLoader.java:164) Summarizing './build-config.json': {
  "areaVisibility" : true,
  "parentStopLinking" : true,
  "osmWayPropertySet" : "germany",
  "subwayAccessTime" : 0,
  "staticBikeParkAndRide" : true,
  "writeCachedElevations" : false,
  "multiThreadElevationCalculations" : false
}
03:20:08.778 ERROR (OTPMain.java:46) An uncaught error occurred inside OTP: Unknown osmWayPropertySet: 'germany'
java.lang.IllegalArgumentException: Unknown osmWayPropertySet: 'germany'
	at org.opentripplanner.graph_builder.module.osm.WayPropertySetSource.fromConfig(WayPropertySetSource.java:29) ~[otp-2.0.0-shaded.jar:1.1]
	at org.opentripplanner.standalone.config.BuildConfig.<init>(BuildConfig.java:319) ~[otp-2.0.0-shaded.jar:1.1]
	at org.opentripplanner.standalone.config.ConfigLoader.loadBuildConfig(ConfigLoader.java:107) ~[otp-2.0.0-shaded.jar:1.1]
	at org.opentripplanner.standalone.configure.OTPConfiguration.<init>(OTPConfiguration.java:61) ~[otp-2.0.0-shaded.jar:1.1]
	at org.opentripplanner.standalone.configure.OTPConfiguration.<init>(OTPConfiguration.java:70) ~[otp-2.0.0-shaded.jar:1.1]
	at org.opentripplanner.standalone.configure.OTPAppConstruction.<init>(OTPAppConstruction.java:50) ~[otp-2.0.0-shaded.jar:1.1]
	at org.opentripplanner.standalone.OTPMain.startOTPServer(OTPMain.java:98) ~[otp-2.0.0-shaded.jar:1.1]
	at org.opentripplanner.standalone.OTPMain.main(OTPMain.java:39) ~[otp-2.0.0-shaded.jar:1.1]
```

I appreciate any hint that sheds light upon that message and the overall API usage.

Cheers!

**Comment by leonardehrenfried** [comment]
You're using OTP 2.0.0 but I added the way property set in dev-2.x. It's not released yet so you need to build a jar from that branch.

**Comment by leonardehrenfried** [comment]
If you trust a stranger on the internet you can get the jars from here: https://otp.leonard.io/snapshots/2.1-SNAPSHOT/ :)

**Comment by dancesWithCycles** [comment]
Hi @leonardehrenfried ,
What is the feature osmWayPropertySet doing? What is the different behaviour with or without this switch set?

Cheers!

**Comment by leonardehrenfried** [comment]
It configures, amongst other things, what is considered a safe route for cyclists.
